# ----------- CONFIGURABLE START -----------
title:            "Read, Write, Think."
description:      "Let's have a bite!"
url:              https://wordbites.github.io # 域名
signoff:          "JL" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: #"liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         书籍
    url:          /book
    external:     false
  - name:         对话
    url:          /interviews
    external:     false
  - name:         标签
    url:          /tags
    external:     false

# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
